name: automation

on:
  push:
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix run .#test
          nix run .#readme > README.md
      - uses: test-room-7/action-update-file@v2.0.0
        with:
          branch: ${{ github.head_ref || github.ref_name }}
          file-path: |
            README.md
          commit-msg: Automatic update
          github-token: ${{ secrets.GITHUB_TOKEN }}
  macos-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix run .#test
          nix run .#readme
